### PR TITLE
Synchronize `Solo`, `Fixed` instances with final GHC 9.2.1 release

### LINKED ISSUE #56: Backport new instances introduced in GHC 9.2
I created this initial list based off of the `base` changelog [here](https://gitlab.haskell.org/ghc/ghc/blob/master/libraries/base/changelog.md), so this may not be comprehensive. If there's something missing, please tell me so that I can get them all in one go (hopefully)!
## New instances
* `Eq1`, `Read1` and `Show1` instances for `Complex`
* `Eq{1,2}`, `Ord{1,2}`, `Show{1,2}` and `Read{1,2}` instances for `(,,)` and `(,,,)`
* `Semigroup` and `Monoid` instances for `Data.Functor.Product` and `Data.Functor.Compose`

### LINKED ISSUE #58: Solo instances
• No instance for (Eq (Solo Char)) arising from a use of ‘hasEq’
  • No instance for (Ord (Solo Char)) arising from a use of ‘hasOrd’
    • No instance for (Bounded (Solo Char))
    • No instance for (Enum (Solo Char))
    • No instance for (Ix (Solo Char)) arising from a use of ‘hasIx’

I'm not sure what would be best plan. Forget about `base-4.15` at this point and just add these instances to `base-orphans`?
OTOH, GHC-9.0.1 is so broken, so maybe it's worth adding these instances to `base-4.15.1.0`, yet it's some extra work...

I'll let you decide

cc @treeowl

### PR DESCRIPTION
**Pull request by RyanGlScott**
This makes two additional GHC 9.2.1–related changes:

* This backports `Eq`, `Ord`, `Bounded`, `Enum`, and `Ix` instances for `Solo`. See https://gitlab.haskell.org/ghc/ghc/-/merge_requests/6453.
* This removes the `Eq1` and `Ord1` instances for `Fixed`, which were ultimately removed from the final GHC 9.2.1 release. See https://gitlab.haskell.org/ghc/ghc/-/merge_requests/6454.

Fixes #58. Fixes #56 (hopefully for good this time).

### CODE REVIEW

**Comment by RyanGlScott** [comment]
@phadej, a handful of questions:

* How do I get `haskell-ci`'s version of `ghcup` to be the latest version (v0.1.17.3)? It looks like `haskell-ci`'s version is using an old version of `ghcup` which doesn't recognize GHC 9.2.1.
* On a related note, I can't actually run the `base-orphan` test suite with GHC 9.2.1 at the moment due to haskellari/splitmix#61. Is it possible to revise `splitmix`'s upper version bounds on `base` on Hackage to allow this? (I've verified that things work locally with `--allow-newer=splitmix:base`.)
* What version should we give to this next `base-orphans` release? This is a breaking API change, so I'm tempted to bump the major version number. What do you think?

**Comment by phadej** [comment]
@RyanGlScott `ghcup` doesn't yet know about GHC-9.2.1. I'll update the `ghcup` version though anyway.

**Comment by RyanGlScott** [comment]
>  `ghcup` doesn't yet know about GHC-9.2.1.

Doesn't it? That's how I'm using GHC 9.2.1 at the moment:

```
$ ghcup --version
The GHCup Haskell installer, version v0.1.17.3
ryanglscott at linferno in ~/Documents/Hacking/Haskell/staging/head.hackage on diagrams-core
$ ghcup list | grep "9\.2"
[ Info  ] downloading: https://raw.githubusercontent.com/haskell/ghcup-metadata/master/ghcup-0.0.6.yaml as file /home/ryanglscott/.ghcup/cache/ghcup-0.0.6.yaml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
✓  ghc   9.2.1    latest,base-4.16.0.0 
```

**Comment by phadej** [comment]
@RyanGlScott looks like I haven't updated my local `ghcup`, my bad. I'll make a release of `splitmix` as soon as its CI finishes.

**Comment by phadej** [comment]
`haskell-ci` is updated, https://hackage.haskell.org/package/splitmix-0.1.0.4 is on hackage.

For the future, the ghcup version can be configured with `ghcup-version: ..` config option.

@hasufell, I'm curious, why new GHC releases require `ghcup` updates?

File: src/Data/Orphans.hs [hunk 1]
```diff
@@ -1663,12 +1667,6 @@ instance Show1 Complex where
       where
         complexPrec = 6
 
-instance Eq1 Fixed where
```
Comment (phadej) [inline src/Data/Orphans.hs:1666]: While this removal is breaking change, I think this is a situation where we can break `SHOULD` in PVP , and do only a minor bump. (that's why it's SHOULD, and not MUST).

Comment (RyanGlScott) [reply src/Data/Orphans.hs:1666]: Very well. I doubt anyone is using these instances anyway, so I don't feel bad about removing these without a major release.

**Comment by hasufell** [comment]
> I'm curious, why new GHC releases require ghcup updates?

The location of the metadata changed to https://github.com/haskell/ghcup-metadata which has better caching than haskell.org servers. I can update the old metadata location manually.
